<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon>AzerothQuesting.ico</ApplicationIcon>
    <AssemblyName>AzerothQuestingCompanion</AssemblyName>
    <RootNamespace>AzerothQuesting.Companion</RootNamespace>
    <Version>0.1.9-beta.7</Version>
    <FileVersion>0.1.8.12</FileVersion>
    <AssemblyVersion>0.1.9.0</AssemblyVersion>
    <InformationalVersion>$(Version)</InformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="AzerothQuesting.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
